[package]
name = "wasm"
version = "0.1.0"
edition = "2024"
authors = ["Toon Verwerft <toonverwerft@gmail.com>"]
description = "A WebAssembly extension for PHP"
readme = "README.md"
license = "MIT"
keywords = ["php", "extension", "webassembly"]
categories = ["wasm"]

[lib]
crate-type = ["cdylib"]

[dependencies]
ext-php-rs = "=0.16.0"
wasmparser = { version = "=0.258.0", default-features = false, features = ["std"] }
wat = "=1.259.0"
wasmtime = { version = "=49.0.1", default-features = false, features = ["cranelift", "runtime", "std", "wat", "gc", "gc-drc", "parallel-compilation", "backtrace", "addr2line", "demangle"] }

[profile.release]
strip = "symbols"
