[package]
name = "typst-example"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
typst = "=0.15.1"
typst-pdf = "=0.15.1"
typst-layout = "=0.15.1"
typst-assets = { version = "=0.15.1", features = ["fonts"] }

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
strip = true
codegen-units = 1
